name: Docker Image CI

on:
  push:
    branches: [ "master" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install node packages
        uses: actions/setup-node@v3
        with:
          node-version: '17.9.0'
          cache: 'npm'
      - run: npm install
      - name: Setup npm ci
        run: npm ci
      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run build
      - name: Build the Docker image
        run: docker build -t ghcr.io/shurenbergen/angular-starter:${{ github.run_number }} .
      
# send notifications to email     
      - name: Send notification
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}  
          # send email to
          to: zantsun@gmail.com
         # from email name
          from: m1sse
